apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mariadb-log
  name: mariadb-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
