apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nextcloud-web
  name: nextcloud-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
